#!/usr/bin/env python3

import urllib.request, json

dictionaries = []
with urllib.request.urlopen("https://services.addons.mozilla.org/api/v4/addons/language-tools/?app=firefox&type=dictionary") as url:
    dictionary_info_list = json.loads(url.read().decode())['results']
    n = 0
    for dictionary_info in dictionary_info_list:
        n += 1
        locale = dictionary_info['target_locale']
        guid = dictionary_info['guid']
        print(str(n) + '/' + str(len(dictionary_info_list)) + ': ' + dictionary_info['target_locale'])
        with urllib.request.urlopen("https://services.addons.mozilla.org/api/v4/addons/search/?guid=" + guid) as url:
            dictionary = json.loads(url.read().decode())['results'][0]
            if dictionary['is_disabled'] or dictionary['status'] != 'public':
                print('skipping ' + locale + ' ' + guid)
                continue
            url = dictionary['current_version']['files'][0]['url']
            urllib.request.urlretrieve(url, 'dictionaries/' + guid + '.xpi')
            dictionaries.append({
                'id': guid,
                'locale': locale,
                'version': dictionary['current_version']['version'],
                'updated': dictionary['last_updated'],
                'users': dictionary['average_daily_users']
            })
dictionaries.sort(key=lambda x: x.get('locale'))
with open('dictionaries/dictionaries.json', 'w', encoding='utf-8') as f:
    json.dump(dictionaries, f, ensure_ascii=False, indent=4)
print('done')