#!/usr/bin/env python3

import json
import os
import sys
import urllib.request
import shutil
import zipfile
import re

def main():
    use_cache = True
    
    script_dir = os.path.dirname(os.path.realpath(__file__))
    if len(sys.argv) < 2 or not os.path.isdir(sys.argv[1]):
        sys.stderr.write("Usage: {0} path/to/zotero/source\n".format(
            os.path.basename(sys.argv[0])))
        return 1
    
    source_dir = sys.argv[1]
    locales_dir = os.path.join(source_dir, 'chrome', 'locale')
    schema_dir = os.path.join(source_dir, 'resource', 'schema')
    
    # AMO download links for Firefox language packs
    language_packs = [
        ["en-US", "https://addons.mozilla.org/firefox/downloads/latest/english-us-language-pack/addon-407142-latest.xpi"],
        ["af", "https://addons.mozilla.org/firefox/downloads/latest/afrikaans-language-pack/addon-5180-latest.xpi", "af-ZA"],
        ["ar", "https://addons.mozilla.org/firefox/downloads/latest/%D8%A7%D9%84%D8%B9%D8%B1%D8%A8%D9%8A%D8%A9-language-pack/addon-417448-latest.xpi"],
        ["bg", "https://addons.mozilla.org/firefox/downloads/latest/%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8-language-pack/addon-417154-latest.xpi", "bg-BG"],
        ["ca", "https://addons.mozilla.org/firefox/downloads/latest/ca-language-pack/addon-5019-latest.xpi", "ca-AD"],
        ["cs", "https://addons.mozilla.org/firefox/downloads/latest/czech-cz-language-pack/addon-417160-latest.xpi", "cs-CZ"],
        ["da", "https://addons.mozilla.org/firefox/downloads/latest/dansk-da-language-pack/addon-376557-latest.xpi", "da-DK"],
        ["de", "https://addons.mozilla.org/firefox/downloads/latest/deutsch-de-language-pack/addon-417164-latest.xpi"],
        ["el", "https://addons.mozilla.org/firefox/downloads/latest/greek-gr-language-pack/addon-417166-latest.xpi", "el-GR"],
        ["es-ES", "https://addons.mozilla.org/firefox/downloads/latest/espa%C3%B1ol-espa%C3%B1a-language-pac/addon-417172-latest.xpi"],
        ["fr", "https://addons.mozilla.org/firefox/downloads/latest/fran%C3%A7ais-language-pack/addon-417178-latest.xpi", "fr-FR"],
        ["et", "https://addons.mozilla.org/firefox/downloads/latest/eesti-et-keele-pakk/addon-7573-latest.xpi", "et-EE"],
        ["eu", "https://addons.mozilla.org/firefox/downloads/latest/basque-language-pack/addon-417174-latest.xpi", "eu-ES"],
        ["fa", "https://addons.mozilla.org/firefox/downloads/latest/persian-ir-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-lang/addon-417456-latest.xpi"],
        ["fi", "https://addons.mozilla.org/firefox/downloads/latest/finnish-language-pack/addon-417176-latest.xpi", "fi-FI"],
        ["he", "https://addons.mozilla.org/firefox/downloads/latest/hebrew-il-language-pack/addon-417186-latest.xpi", "he-IL"],
        ["hr", "https://addons.mozilla.org/firefox/downloads/latest/hrvatski-hr-language-pack/addon-417190-latest.xpi", "hr-HR"],
        ["hu", "https://addons.mozilla.org/firefox/downloads/latest/magyar-nyelvi/addon-13589-latest.xpi?src=dp-btn-primary", "hu-HU"],
        ["id", "https://addons.mozilla.org/firefox/downloads/latest/indonesian-langpack/addon-6293-latest.xpi", "id-ID"],
        ["is", "https://addons.mozilla.org/firefox/downloads/latest/icelandic-is-language-pack/addon-417192-latest.xpi", "is-IS"],
        ["it", "https://addons.mozilla.org/firefox/downloads/latest/italiano-it-language-pack/addon-417194-latest.xpi", "it-IT"],
        ["ja", "https://addons.mozilla.org/firefox/downloads/latest/japanese-language-pack-1/addon-417196-latest.xpi", "ja-JP"],
        ["km", "https://addons.mozilla.org/firefox/downloads/latest/%E1%9E%81%E1%9E%98%E1%9E%9A-language-pack/addon-417200-latest.xpi"],
        ["ko", "https://addons.mozilla.org/firefox/downloads/latest/korean-kr-language-pack/addon-417204-latest.xpi", "ko-KR"],
        ["lt", "https://addons.mozilla.org/firefox/downloads/latest/lietuvi%C5%B3-language-pack/addon-417210-latest.xpi", "lt-LT"],
        ["nb-NO", "https://addons.mozilla.org/firefox/downloads/latest/norsk-bokm%C3%A5l-no-language-pa/addon-417220-latest.xpi"],
        ["nn-NO", "https://addons.mozilla.org/firefox/downloads/latest/norsk-nynorsk-no-language-p/addon-417224-latest.xpi"],
        ["nl", "https://addons.mozilla.org/firefox/downloads/latest/nederlands-nl-language-pack/addon-417222-latest.xpi", "nl-NL"],
        ["pl", "https://addons.mozilla.org/firefox/downloads/latest/polski-language-pack/addon-417230-latest.xpi", "pl-PL"],
        ["pt-BR", "https://addons.mozilla.org/firefox/downloads/latest/firefox-br/addon-4851-latest.xpi"],
        ["pt-PT", "https://addons.mozilla.org/firefox/downloads/latest/portugu%C3%AAs-portugal-language/addon-417232-latest.xpi"],
        ["ro", "https://addons.mozilla.org/firefox/downloads/latest/romanian-language-pack/addon-4551-latest.xpi", "ro-RO"],
        ["ru", "https://addons.mozilla.org/firefox/downloads/latest/russian-ru-language-pack/addon-417236-latest.xpi", "ru-RU"],
        ["sk", "https://addons.mozilla.org/firefox/downloads/latest/slovak-sk-language-pack/addon-417238-latest.xpi", "sk-SK"],
        ["sl", "https://addons.mozilla.org/firefox/downloads/latest/slovenski-jezik-language-pa/addon-417240-latest.xpi", "sl-SI"],
        ["sr", "https://addons.mozilla.org/firefox/downloads/latest/%D1%81%D1%80%D0%BF%D1%81%D0%BA%D0%B8-sr-language-pack/addon-417246-latest.xpi", "sr-RS"],
        ["sv-SE", "https://addons.mozilla.org/firefox/downloads/latest/svenska-se-language-pack/addon-417248-latest.xpi", "sv-SE"],
        ["th", "https://addons.mozilla.org/firefox/downloads/latest/thai-language-pack/addon-417252-latest.xpi", "th-TH"],
        ["tr", "https://addons.mozilla.org/firefox/downloads/latest/t%C3%BCrk%C3%A7e-tr-language-pack/addon-417254-latest.xpi", "tr-TR"],
        ["uk", "https://addons.mozilla.org/firefox/downloads/latest/ukrainian-language-pack/addon-8141-latest.xpi", "uk-UA"],
        ["vi", "https://addons.mozilla.org/firefox/downloads/latest/vietnamese-language-pack/addon-8228-latest.xpi", "vi-VN"],
        ["zh-CN", "https://addons.mozilla.org/firefox/downloads/latest/chinese-simplified-zh-cn-la/addon-417256-latest.xpi"],
        ["zh-TW", "https://addons.mozilla.org/firefox/downloads/latest/traditional-chinese-zh-tw-l/addon-417258-latest.xpi"]
    ]
    
    # Can be a string or a dict containing 'file' and 'patterns'
    entries = [
        "chrome/{0}/locale/{0}/global/dateFormat.properties",
        "chrome/{0}/locale/{0}/global/editMenuOverlay.dtd",
        {
            "file": "browser/chrome/{0}/locale/browser/browser.dtd",
            "grep_patterns": [
                "preferencesCmd"
            ]
        }
    ]
    
    extracted_files = {}
    for entry in entries:
        entry_filename = get_entry_filename(entry)
        if entry_filename != 'dateFormat.properties':
            extracted_files[entry_filename] = set()
    
    date_formats = {}
    
    first = True
    for pack in language_packs:
        lang, url, *rest = pack
        
        if len(rest):
            locale = rest[0]
        else:
            locale = lang
        
        pack_dir = os.path.join(script_dir, 'packs', lang)
        locale_dir = os.path.join(locales_dir, locale, 'zotero', 'mozilla')
        
        if not os.path.exists(pack_dir):
            os.makedirs(pack_dir)
        if not os.path.exists(locale_dir):
            os.mkdir(locale_dir)
            
        file_name = url.split("/")[-1]
        pack_file = os.path.join(pack_dir, file_name)
        
        if not first:
            print()
        first = False
        if use_cache and os.path.isfile(pack_file):
            print("Using cached file for " + pack_file)
        else:
            print("Downloading " + url)
            with urllib.request.urlopen(url) as response, open(pack_file, 'wb') as f:
                code = response.getcode()
                if code != 200:
                    sys.sterr.write("Got {0} for {1}\n".format(code, url))
                    return 1
                
                shutil.copyfileobj(response, f)
        
        # Unzip selected files straight to target locale dirs
        with zipfile.ZipFile(pack_file, "r") as zip_ref:
            for entry in entries:
                entry_path = get_entry_path(entry)
                entry_filename = get_entry_filename(entry)
                formatted_path = entry_path.format(lang)
                
                try:
                    zip_ref.getinfo(formatted_path)
                except KeyError:
                    print("'{0}' not found in {1}".format(formatted_path, pack_file))
                    continue
                
                with zip_ref.open(formatted_path) as source:
                    # Add date formats to JSON object
                    if entry_filename == 'dateFormat.properties':
                        date_formats[locale] = {
                            "short": [],
                            "long": []
                        }
                        pattern = re.compile(r"^month\.\d+\.(Mmm|name)\s*=\s*(.+)$")
                        for line in source:
                            matches = pattern.match(str(line, 'utf-8'))
                            if matches:
                                if matches.group(1) == "Mmm":
                                    date_formats[locale]["short"].append(
                                        matches.group(2).strip()
                                    )
                                else:
                                    date_formats[locale]["long"].append(
                                        matches.group(2).strip()
                                    )
                    # Extract other files
                    else:
                        target_path = os.path.join(locale_dir, entry_filename)
                        print("Extracting " + target_path)
                        with open(target_path, "wb") as target:
                            copied = False
                            if isinstance(entry, dict) and entry['grep_patterns']:
                                lines_to_write = []
                                for line in source:
                                    line_str = str(line, 'utf-8')
                                    for p in entry['grep_patterns']:
                                        if p in line_str:
                                            lines_to_write.append(line)
                                            continue
                                
                                if len(lines_to_write):
                                    target.write(
                                        # BOM is required for Firefox to read file
                                        '\ufeff'.encode('utf-8')
                                        + b''.join(lines_to_write)
                                    )
                                    copied = True
                            else:
                                shutil.copyfileobj(source, target)
                                copied = True
                            
                            if copied:
                                extracted_files[entry_filename].add(locale)
    
    print()
    
    # Copy en-US files to any locales that didn't have localized versions
    en_locale_dir = os.path.join(locales_dir, 'en-US', 'zotero', 'mozilla')
    locales = set(os.listdir(locales_dir))
    for entry_filename, existing_locales in extracted_files.items():
        missing = locales.difference(existing_locales)
        
        for locale in missing:
            dest_dir = os.path.join(locales_dir, locale, 'zotero', 'mozilla')
            dest_file = os.path.join(dest_dir, entry_filename)
            if not os.path.exists(dest_dir):
                os.mkdir(dest_dir)
            source_file = os.path.join(en_locale_dir, entry_filename)
            print("Copying en-US {0} to {1}".format(entry_filename, dest_file))
            shutil.copyfile(source_file, dest_file)
    
    print()
    
    # Write dateFormats.json from the extracted data
    date_formats_path = os.path.join(schema_dir, 'dateFormats.json')
    print("Writing " + date_formats_path);
    with open(date_formats_path, 'w') as f:
        f.write(json.dumps(date_formats, indent='\t', ensure_ascii=False))


def get_entry_path(entry):
    if isinstance(entry, str):
        path = entry
    else:
        path = entry['file']
    return path


def get_entry_filename(entry):
    path = get_entry_path(entry)
    return path.split("/")[-1]


if __name__ == '__main__':
    sys.exit(main())
