#!/bin/bash -e

#
# Move update-build.rdf to download directory with given version number
# and set up symlink to update.rdf
#

. config.sh

if [ -z "$1" ]; then
	echo "Usage: $0 version"
	exit 1
fi

VERSION="$1"

if ! grep --quiet "<version>$VERSION" $BUILD_DIR/update-build.rdf ; then
	echo "$VERSION not found in update-build.rdf"
	exit 1
fi

if [ -f "download/update-$VERSION.rdf" ]; then
	echo "update-$VERSION.rdf already exists"
	exit 1
fi

mv $BUILD_DIR/update-build.rdf download/update-$VERSION.rdf
cd download
ln -f -s update-$VERSION.rdf update.rdf

ls -laG update*rdf
echo
cat update.rdf
